FROM node:16.13.0-alpine

# Create tests directory
WORKDIR /usr/src/example-tests

COPY . .
RUN npm install

# Setup env
ENV APP_URL=$APP_URL
ENV SELENIUM_HUB_URL=$SELENIUM_HUB_URL
# Drill4J related params
ENV DRILL4J_ADMIN_BACKEND_URL=$DRILL4J_ADMIN_BACKEND_URL
ENV DRILL4J_DEVTOOLS_PROXY_URL=$DRILL4J_DEVTOOLS_PROXY_URL
ENV DRILL4J_AGENT_ID=$DRILL4J_AGENT_ID
# ENV DRILL4J_GROUP_ID=$DRILL4J_GROUP_ID

# Launch
EXPOSE 8080

CMD npm run test_with_recommendations
