version: '3'

services:
  example-tests:
    image: drill4j/example-js-selenium-mocha
    environment:
      APP_URL: ${APP_URL}
      SELENIUM_HUB_HOST: ${SELENIUM_HUB_HOST}
      SELENIUM_HUB_PORT: ${SELENIUM_HUB_PORT}

      DRILL4J_ADMIN_BACKEND_URL: ${DRILL4J_ADMIN_BACKEND_URL}
      DRILL4J_DEVTOOLS_PROXY_URL: ${DRILL4J_DEVTOOLS_PROXY_URL}
      DRILL4J_AGENT_ID: ${DRILL4J_AGENT_ID}

      DEBUG: 'drill:*'
      DEBUG_COLORS: 'true'
      FORCE_COLOR: '3'
      DEBUG_LOG_LEVEL: '4'

    networks:
      grid:

networks:
  grid:
