version: '3'
services:
  # selenoid:
  #   network_mode: bridge
  #   image: aerokube/selenoid:latest-release
  #   volumes:
  #     - '.:/etc/selenoid'
  #     - './target:/output'
  #     - '//var/run/docker.sock:/var/run/docker.sock' # for windows
  #     - './target:/opt/selenoid/video'
  #   environment:
  #     - OVERRIDE_VIDEO_OUTPUT_DIR=/selenoid-data/video
  #   command: ['-conf', '/etc/selenoid/browsers.json', '-video-output-dir', '/opt/selenoid/video', '-timeout=10h']
  #   ports:
  #     - '4444:4444'

  selenoid-ui:
    image: 'aerokube/selenoid-ui:latest'
    ports:
      - '8089:8080'
    command: ['--selenoid-uri', 'http://host.docker.internal:4444']
